### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by gobind88sharma** [jwoodcock/OhMyEmma#8]
How to pass pagination or other parameters?

**Comment by jwoodcock** [comment]
So ultimately it comes down to what Emma supports but most `get` methods support passing in html parameters as an array. 

If you look here `https://github.com/jwoodcock/OhMyEmma/blob/master/Source/Kite/OhMyEmma/Interfaces/Members.php#L61`
you will see that the `getMembers` method has a 3rd parameter that  you can pass which is the html query string that needs to be sent.

**Comment by gobind88sharma** [comment]
please add pagination on other classes too like Mailings, Responses etc.
Thanks
